#!/usr/bin/env bash
#
# This script installs jeff-dh's Solid Python branch

set -euo pipefail

function main() {
  identify-platform
  install-bosl2

  install-poetry
  poetry install

  # install-solid-python
}

function install-poetry() {
  if ! has-command poetry; then
    curl -sSL https://install.python-poetry.org | python3 -
  fi
}

function has-command() {
  type "$1" > /dev/null 2>&1
}

function identify-platform() {
  if [ "$(uname -s)" = "Darwin" ]; then
    PLATFORM=mac
    OPENSCAD_LIB_DIR="$HOME/Documents/OpenSCAD/libraries"
  elif [[ "$(cat /proc/version)" =~ 'microsoft' ]]; then
    PLATFORM=linux
    OPENSCAD_LIB_DIR="$HOME/.local/share/OpenSCAD/libraries"
  else
    PLATFORM=wsl
    WIN_USERNAME="$(wsl-get-env USERNAME)"
    WIN_HOME="/mnt/c/Users/$WIN_USERNAME"
    OPENSCAD_LIB_DIR="$WIN_HOME/Documents/OpenSCAD/libraries"
  fi

  echo "--------------------------------------------------"
  echo "Platform:      $PLATFORM"
  echo "OpenSCAD libs: $OPENSCAD_LIB_DIR"
  echo "--------------------------------------------------"
  echo
}

function install-bosl2() {
  if [ -e "$OPENSCAD_LIB_DIR/BOSL2" ]; then
    echo "- OpenSCAD BOSL2 extensions already installed."
  else
    echo "- Installing OpenSCAD BOSL2 extensions..."
    git clone --depth=1 https://github.com/revarbat/BOSL2 \
      "$OPENSCAD_LIB_DIR/BOSL2"
  fi
}

function install-solid-python() {
  if pip3 list | grep solid > /dev/null; then
    echo "- SolidPython already installed."
  else
    echo "- Installing SolidPython..."
    pip install git+https://github.com/jeff-dh/SolidPython.git@exp_solid
  fi
}

function wsl-get-env() {
  cmd.exe /c "<nul set /p=%$1%" 2> /dev/null || true
}

main
